development:
  adapter: mysql2
  database: influence_dev
  username: root
  password: 1Keyword1
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: influence_test
  username: root
  password: 1Keyword1
  host: localhost
  encoding: utf8
  collation: utf8_general_ci

production:
  adapter: mysql2
  database: influence_prod
  username: root
  password: 1Keyword1
  host: localhost
