development:
  adapter: postgresql
  encoding: unicode
  database: influence_dev
  pool: 5
  username: jmoscat
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: influence_test
  pool: 5
  username: jmoscat
  password: